version: "1.1"
stages:
- stage:
  - git-checkout:
      alias: repo
      params:
        depth: 1
- stage:
  - buildpack:
      alias: package-backend
      params:
        context: ${repo}
        modules:
        - name: apm-demo-api
          path: apm-demo-api
- stage:
  - release:
      alias: release
      params:
        dice_development_yml: ${repo}/dice_development.yml
        dice_production_yml: ${repo}/dice_production.yml
        dice_staging_yml: ${repo}/dice_staging.yml
        dice_test_yml: ${repo}/dice_test.yml
        dice_yml: ${repo}/dice.yml
        replacement_images:
        - ${package-backend}/pack-result
- stage:
  - dice:
      alias: deploy
      params:
        dice_yml: ${repo}/dice.yml
        release_id_path: ${release}
        replacement_images:
        - package/pack-result
        - package-ui/pack-result
        time_out: 300
