version: "1.0"
stages:
  - name: "repo"
    tasks:
      - get: "repo"
        params:
          depth: 1
  - name: "buildpack"
    tasks:
      - aggregate:
          - put: "package-backend"
  - name: "deploy"
    tasks:
      - put: "deploy"
        params:
          dice_yml: "repo/dice.yml"
          time_out: 300
          replacement_images:
            - "package/pack-result"
            - "package-ui/pack-result"
resources:
  - name: "repo"
    type: "git"
    source:
      uri: "((gittar.repo))"
      branch: "((gittar.branch))"
      username: "((gittar.username))"
      password: "((gittar.password))"
  - name: "package-backend"
    type: "buildpack"
    source:
      context: "repo"
      modules:
        - name: "apm-demo-api"
          path: "apm-demo-api"
      bp_repo: "http://git.terminus.io/buildpacks/dice-bpack-termjava.git"
      bp_ver: "feature/agent-preview"
      bp_args:
        USE_PREVIEW_AGENT: "true"
  - name: "deploy"
    type: "dice"
    source:
      app_id: "((dice.id))"
      uri: "((dice.url))"
      operator_id: "((dice.operator.id))"
      workspace: "((dice.env))"
      branch: "((gittar.branch))"
envs: {}
