version: "1.1"
stages:
- stage:
  - git-checkout:
      alias: repo
      description: ""
      params:
        depth: 1
- stage:
  - buildpack:
      alias: package-ui
      description: ""
      params:
        bp_args:
          DEP_CMD: "yum install -y gcc-c++ && yum install -y make && npm ci"
        bp_repo: http://git.terminus.io/buildpacks/dice-bpack-termnodejs.git
        bp_ver: feature/agent-preview
        context: ${repo}
        modules:
        - name: apm-demo-ui
          path: .
- stage:
  - release:
      alias: release
      description: ""
      params:
        dice_development_yml: ${repo}/dice_development.yml
        dice_production_yml: ${repo}/dice_production.yml
        dice_staging_yml: ${repo}/dice_staging.yml
        dice_test_yml: ${repo}/dice_test.yml
        dice_yml: ${repo}/dice.yml
        replacement_images:
        - ${package-ui}/pack-result
- stage:
  - dice:
      alias: deploy
      description: ""
      params:
        dice_yml: ${repo}/dice.yml
        release_id_path: ${release}
        replacement_images:
        - pack-result
        time_out: 300
